id: ADD2A843A
base_file: f86AC.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 04:56:53.134359
  last_modified_at: 2022-05-31 04:56:53.134370
