id: ADD2A843A
base_file: f9EC2.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 04:56:53.139077
  last_modified_at: 2022-05-31 04:56:53.139084
